# Generated by Django 4.1.7 on 2023-03-30 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=40, verbose_name="عنوان")),
                ("url", models.URLField(verbose_name="آدرس")),
                (
                    "description",
                    models.TextField(max_length=120, verbose_name="توضیحات"),
                ),
                ("vote", models.IntegerField(default=0, verbose_name="رای")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "خبر",
                "verbose_name_plural": "اخبار",
            },
        ),
    ]
