# Generated by Django 4.1.7 on 2023-03-30 17:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="News",
            new_name="Link",
        ),
    ]
