# Generated by Django 4.1.7 on 2023-03-31 00:02

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0002_rename_news_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="link",
            name="vote",
        ),
        migrations.AddField(
            model_name="link",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 31, 0, 2, 45, 345078, tzinfo=datetime.timezone.utc
                ),
                verbose_name="ایجاد",
            ),
        ),
        migrations.AddField(
            model_name="link",
            name="dislike",
            field=models.ManyToManyField(
                related_name="dislikes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="نپسندیدن",
            ),
        ),
        migrations.AddField(
            model_name="link",
            name="like",
            field=models.ManyToManyField(
                related_name="likes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="پسندیدن",
            ),
        ),
    ]
