# Generated by Django 4.1.7 on 2023-03-31 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_remove_link_vote_link_created_link_dislike_link_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
        ),
    ]
